seed: 42

augmentations: {'AddToBrightness': [-100, 100], 'AddToHue': [-100, 100], 'Rotate': [-40, 40],   'Translate': [-0.4, 0.4], 'Scale': [0.8, 1.2], 'AddToSaturation': [-100, 100]}
n_aug: 10
expl_methods: [Gradients, InputGradients, IntegratedGradients, Deconvolution, GuidedBackprop, zennit-EpsilonPlusFlat, zennit-EpsilonGammaBox, zennit-EpsilonAlpha2Beta1Flat]
background: constant
n_to_expl: 10
models_to_process: [ResNet50_full]
save_expl: False
path_expl: /explanations/
only_correct: False
probab_drop: 0.1
N: 100

model_name: resnet50
use_model_ema: True
checkpoint_path: /models/ResNet50_full.pth
pretrained: True
trained_with_torchvision: True
